blank_issues_enabled: false
contact_links:
  - name: Duino support
    url: https://help.Duino.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the Duino Python library.
      If you're having general trouble with the Duino API, please visit our help center to get support.
