name: CI
on:
  pull_request:
    branches:
      - main
      - next

jobs:
  detect_breaking_changes:
    runs-on: 'ubuntu-latest'
    name: detect-breaking-changes
    if: github.repository == 'Duino/Duino-python'
    steps:
      - name: Calculate fetch-depth
        run: |
          echo "FETCH_DEPTH=$(expr ${{ github.event.pull_request.commits }} + 1)" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Ensure we can check out the pull request base in the script below.
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Set up Rye
        uses: eifinger/setup-rye@c694239a43768373e87d0103d7f547027a23f3c8
        with:
          version: '0.44.0'
          enable-cache: true
      - name: Install dependencies
        run: |
          rye sync --all-features
      - name: Detect removed symbols
        run: |
          rye run python scripts/detect-breaking-changes.py "${{ github.event.pull_request.base.sha }}"

      - name: Detect breaking changes
        run: |
          test -f ./scripts/detect-breaking-changes || { echo "Missing scripts/detect-breaking-changes"; exit 1; }
          ./scripts/detect-breaking-changes ${{ github.event.pull_request.base.sha }}

  agents_sdk:
    runs-on: 'ubuntu-latest'
    name: Detect Agents SDK regressions
    if: github.repository == 'Duino/Duino-python'
    steps:
      # Setup this sdk
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          path: Duino-python

      - name: Set up Rye
        uses: eifinger/setup-rye@c694239a43768373e87d0103d7f547027a23f3c8
        with:
          version: '0.44.0'
          enable-cache: true
          working-directory: Duino-python

      - name: Install dependencies
        working-directory: Duino-python
        run: |
          rye sync --all-features

      # Setup the agents lib
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: Duino/Duino-agents-python
          path: Duino-agents-python

      - name: Setup uv
        uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081 # v5
        with:
          enable-cache: true

      - name: Link to local SDK
        working-directory: Duino-agents-python
        run: uv add ../Duino-python

      - name: Install dependencies
        working-directory: Duino-agents-python
        run: make sync

      - name: Run integration type checks
        working-directory: Duino-agents-python
        run: make mypy
